---
- name: get mesosphere rpm
  get_url: >-
    url={{mesosphere_rpm_url}}
    dest=/tmp/{{mesosphere_rpm}}
    owner=root
    group=root
    mode=0644
    
- name: add the mesosphere repo
  package: >
    name=/tmp/{{mesosphere_rpm}}
    state=present

- name: mkdir /etc/mesos
  file: >
    owner=root
    group=root
    mode=0755
    path=/etc/mesos
    state=directory
  
- name: install /etc/mesos/zk
  template: >
    src=etc/mesos/zk.j2
    dest=/etc/mesos/zk
    owner=root
    group=root
    mode=0644

